# Generated by Django 3.2.3 on 2021-05-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('quantity', models.IntegerField()),
                ('brought_rate', models.IntegerField()),
                ('brought_date', models.DateField()),
                ('sold_rate', models.IntegerField()),
                ('sold_date', models.DateField()),
            ],
        ),
    ]
