# Generated by Django 3.2.3 on 2021-05-29 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharedetail', '0002_sharesold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharebrought',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brought_user', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharesold',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sold_user', to='user.user'),
            preserve_default=False,
        ),
    ]
