# Generated by Django 3.2.3 on 2021-05-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedetail', '0003_auto_20210530_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharebrought',
            name='brought_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sharesold',
            name='brought_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sharesold',
            name='sold_rate',
            field=models.FloatField(),
        ),
    ]
